In [15]:
import torch
x = torch.empty(5, 3)
x = torch.rand(5, 3)
x = torch.zeros(5, 3, dtype=torch.long)
x = torch.tensor([5.5, 3])
x = x.new_ones(5, 3, dtype=torch.double)
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[ 0.3058, -1.2311,  0.2594],
        [ 0.3707, -0.6336,  1.1749],
        [-0.4051,  0.4016,  1.1909],
        [ 0.4499, -0.3473,  0.1786],
        [-1.3147,  0.2483, -0.0051]])
torch.Size([5, 3])


In [18]:
y = torch.rand(5, 3)
y

tensor([[0.6260, 0.6784, 0.1697],
        [0.4688, 0.5834, 0.0897],
        [0.2204, 0.0518, 0.2144],
        [0.5400, 0.0700, 0.6336],
        [0.5112, 0.9123, 0.3233]])

In [21]:
print(torch.add(x, y))
result = torch.empty(5, 3)
torch.add(x, y, out=result)
# any operation that mutates a tensor in-place is post-fixed
# with an _ . For example: x.copy_(y), x.t_()
# will change x
y.add_(x)

tensor([[ 0.9318, -0.5528,  0.4292],
        [ 0.8395, -0.0502,  1.2646],
        [-0.1847,  0.4534,  1.4053],
        [ 0.9899, -0.2773,  0.8122],
        [-0.8035,  1.1606,  0.3182]])
tensor([-1.2311, -0.6336,  0.4016, -0.3473,  0.2483])


In [24]:
print(x[:, 1])
# if you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(-1, 8)
z = x.view(-1, 2, 4)
print(x.size(), y.size(), z.size())

tensor([[-0.0567, -0.9079,  0.3804, -0.5696],
        [ 1.0613,  1.0620, -0.3570,  0.1030]])
torch.Size([4, 4]) torch.Size([2, 8]) torch.Size([2, 2, 4])


In [25]:
# if you have a one element tensor, use.item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.0661])
2.066114902496338


In [26]:
# implement the network using numpy
import numpy as np

# N is batch size; D_in is input dimension
# H is hidden dimension; D_out is output dimension

N, D_in, H, D_out = 64, 1000, 100, 10

# create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random. randn(H, D_out)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    
    #Compute and print loss
    loss = np.square(y_pred-y).sum()
    print(t, loss)
    
    # Backprop to compute gradient of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    # Update weight
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    

0 31746839.663173623
1 29398788.327436335
2 31696752.49791666
3 33534076.274362758
4 30425900.396040745
5 22427780.52101308
6 13270342.343572147
7 6914569.617021697
8 3532537.4693149813
9 1980931.761589724
10 1270164.2712220363
11 919696.1258223027
12 722114.6667584493
13 594321.935534439
14 501956.11641762045
15 430433.68474133906
16 372620.931260184
17 324711.28991782246
18 284408.5594293276
19 250238.27534570522
20 220990.29355209836
21 195842.15881316035
22 174134.2653017016
23 155323.79372610466
24 138929.54651294844
25 124583.26730077242
26 111984.85013356383
27 100884.39760766384
28 91077.2661092757
29 82384.45700601439
30 74658.97209072708
31 67781.54944504393
32 61646.32651235578
33 56159.25341929644
34 51240.27200974333
35 46821.09796645605
36 42842.14329868824
37 39253.43368063192
38 36012.087007156515
39 33079.810436825486
40 30423.14922461459
41 28010.75419246264
42 25818.6438686241
43 23822.259531844164
44 22002.057492072523
45 20341.2997037104
46 18824.194370784255
47 17

In [29]:
# use Tensors
import torch
dtype = torch.float
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)
    
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    

cuda:0
99 222.92034912109375
199 0.5531930923461914
299 0.0025878818705677986
399 0.00010113709868164733
499 2.49585609708447e-05


In [5]:
# Tensors and autograd
import torch
dtype = torch.float
device = torch.device("cpu")

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())
    loss.backward()
    
    # Wrap in torch.no_grad() beacause weights have requires_grad=True, but we don't need to track this update in autograd
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

99 1114.3544921875
199 13.568634033203125
299 0.24144330620765686
399 0.0050233290530741215
499 0.0002936195523943752


In [7]:
# Define new autograd functions
import torch

class MyReLU(torch.autograd.Function):
    """
    We can implement our own custom autograd Functions by subclassing torch.autograd.Function
    and implementing the forward and backward passes which operate on Tensors
    """
    
    @staticmethod
    def forward(ctx, input):
        """
        :param ctx: is a context object that can be used to stash information for backward computation
        :param input:  A Tensor containing the input 
        :return: A Tensor containing the output
        You can cache arbitrary objects for use in the backward pass using the ctx.save_for_backward method.
        """
        ctx.save_for_backward(input)
        return input.clamp(min=0)
    
    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input
import torch
dtype = torch.float
device = torch.device("cpu")

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # to apply our Function, we use Function.apply method. We alias this as 'relu'
    relu = MyReLU.apply
    y_pred = relu(x.mm(w1)).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())
    loss.backward()
    
    # Wrap in torch.no_grad() beacause weights have requires_grad=True, but we don't need to track this update in autograd
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

99 387.7276916503906
199 1.9804493188858032
299 0.016391541808843613
399 0.00034282461274415255
499 5.0839284085668623e-05


In [ ]:
# nn module
import torch
N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# The nn package also contains definitions of popular loss functions; in this
# case we will use Mean Squared Error (MSE) as out loss function

loss_fn = torch.nn.MSELoss(reduction='sum')
learning_rate = 1e-4

for t in range(500):
    # Forward pass: compute y_pred by passing x to the model. Module objects
    # override __call__ operator so you can call them like functions. When
    # doing so you pass a Tensor of input data to the Module an d it produces
    # a Tensor of output data.
    y_pred = model(x)
    
    # Compute and print loss. We pass Tensors containing the predicted and true
    # values of y, and the loss function returns a Tensor containing the lloss
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())
    
    # Zero the gradients before running the backward pass
    model.zero_grad()
    
    # Backward pass: compute gradient of the loss with respect to all the learnable 
    # parameterers of the model. Internally, the parameters of each Modules are stored
    # in Tensors withe requires_grad=True, so this call will compute gradients for all learnable parameters in the model
    loss.backward()
    
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

In [ ]:
# optim Up to this point we have updated the weights of our models by manually mutating the
# Tensors holding learnable parameters(with torch.no_grad() or .data to avoid tracking history in autograd
# This is not a huge burden for simple optimization algorithms like stochastic gradient descent,
# but in practice we often tran neural networks using more sophisticated optimizers like AdaGrad, RMSProp, Adam,etc

# The optim package in Pytorch abstracts the idea of an optimization algorithm and provides implementations
# of commonly used optimization algorithms.

import torch

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of 
# the model for us. Here we use Adam; the optim package contains many other 
# optimization algorithms. The first argument to the Adam constructor tells the 
# optimizer which Tensors it should update
learning_rate = 1e-4 
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(500):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())
    
    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables if will update (which are the learnable weights
    # of the model). This is because by default, gradients are accumulated in buffers
    # (i.e, not overwritten) whenever .backward() is called. Checkout docs of torch.autograd.backward for more details
    
    optimizer.zero_grad()
    loss.backward()
    
    # Calling the step function on an Optimizer makes an update to its parameters
    optimizer.step()

In [8]:
# PyTorch: Custom nn Modules
"""
Sometimes you will want to specify models that are more complex than a sequence of existing Moduels;
for these cases you can define your own Modules by subclassing nn.Module and defining a forward which
receives input Tensors and produces output Tensors using other modules or other autograd operations on Tensors
"""
import torch 

class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them 
        as member variables
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)
    
    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for t in range(500):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

99 666.1162109375
199 648.470458984375
299 631.3606567382812
399 614.808349609375
499 598.757568359375


In [1]:
# Pytorch: Control Flow + Weight Sharing
"""
As an example of dynamic graphs and weights sharing, we implement a very strange model:
a fully-connected ReLU network that on each forward pass chooses a random number between
1 and 4 and uses that many hidden layers, reusing the same weights multiple times to compute 
the innermost hidden layers
For this model we can normal Python flow control to implement the loop, and we can implement weight
sharing among the innermost layers by simply reusing the same Module multiple times when defining the 
forward pass
"""
import random
import torch
class DynamicNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we construct three nn.Linear instances that we will use in the
        forward pass 
        """
        super(DynamicNet, self).__init__()
        self.input_linear = torch.nn.Linear(D_in, H)
        self.hidden_linear = torch.nn.Linear(H, H)
        self.output_linear = torch.nn.Linear(H, D_out)
        
    def forward(self, x):
        """
        For the forward pass of the model, we randomly choose either 0, 1, 2 or 3
        and reuse the middle_layer Module that many times to compute hidden layer representation
        Since each forward pass bulids a dynamic computation graph, we can use normal Python 
        control-flow operators like loops or conditional statements when defining the forward pass
        of the model.
        Here we also see that it is perfectly safe to reuse the same Module many times when defining
        a computational graph. This is a big improvement from Lua Torch, where each Module could be used
        only once
        """
        h_relu = self.input_linear(x).clamp(min=0)
        for _ in range(random.randint(0, 3)):
            h_relu = self.hidden_linear(h_relu).clamp(min=0)
        y_pred = self.output_linear(h_relu)
        return y_pred

N, D_in, H, D_out = 64, 100, 1000, 10

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = DynamicNet(D_in, H, D_out)
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

for t in range(500):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    
    if t % 100 == 99:
        print(t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
            

99 46.20490264892578
199 9.365419387817383
299 45.42475891113281
399 17.987531661987305
499 7.554983139038086
